[AbilityEditor.X2DLCInfo_AbilityEditor]
; Examples:

; This will allow Ranger to have an action after Slash
+AbilityEdits=( \\
    Ability=SwordSlice, \\
    Costs=( \\
        ( \\
            Class="X2AbilityCost_ActionPoints", \\
            SetNumPoints=true, \\
            NumPoints=1, \\
            SetConsumeAllPoints=true, \\
            ConsumeAllPoints=true, \\
            DoNotConsumeAllSoldierAbilities=(Blademaster) \\
        ), \\
        ( \\
            Class=X2AbilityCost_Charges, \\
            SetNumCharges=true, \\
            NumCharges=2 \\
        ) \\
    ), \\
    Charges=( \\
        Class="X2AbilityCharges", \\
        SetInitialCharges=true, \\
        InitialCharges=5, \\
        BonusCharges=( \\
            ( \\
                AbilityName=Blademaster, \\
                SetNumCharges=true, \\
                NumCharges=3 \\
            ) \\
        ) \\
    ), \\
    Cooldown=( \\
        Class="X2AbilityCooldown", \\
        SetNumTurns=true, \\
        NumTurns=5, \\
        AdditionalCooldowns=( \\
            ( \\
                AbilityName=Blademaster, \\
                SetNumTurns=true, \\
                NumTurns=3 \\
            ) \\
        ) \\
    ) \\
)

; Gives 9 charges of Scanning Protocol, is a free action and can be used every two turns
;+Abilities = (AbilityName=ScanningProtocol, Cooldown=2, Charges=9, FreeAction=true)

; Restoration grants 3 extra charges of Heals
;+Abilities = (AbilityName=GremlinHeal, Charges=2, BonusChargeWith[0]=(BonusAbilityName=RestorativeMist, NumBonusCharges=3) )

+AbilityEdits=( \\
    Ability=AidProtocol, \\
    Cooldown=( \\
        Class="XComGame.X2AbilityCooldown_PerPlayerType", \\
        SetNumTurns=true, \\
        NumTurns=9, \\
        SetNumTurnsForAI=true, \\
        NumTurnsForAI=1 \\
    ) \\
)
